server:
    port: 8080

spring:
    profiles:
        active: dev
    data:
        mongodb:
            uri: mongodb://admin:admin@ds133964.mlab.com:33964/rmsdevdb
            port: 33964
            host: ds133964.mlab.com
            database: rmsdevdb
            username: admin
            password: admin
        rest:
          base-path: /developer
