server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        mongodb:
            database: heroku_qbd72rv8
        rest:
          base-path: /developer
          
          
          
          
          
